apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pensjon-regler-beregn"
  namespace: "teampensjon"
  labels:
    team: "teampensjon"
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/index.html"
    initialDelay: 40
    timeout: 3
  readiness:
    path: "/index.html"
    initialDelay: 40
    timeout: 3
  resources:
    limits:
      cpu: "1"
      memory: "2048Mi"
    requests:
      cpu: "100m"
      memory: "512Mi"
  ingresses:
    - "https://pensjon-regler-beregn.dev.adeo.no"
    - "https://pensjon-regler-beregn.dev-fss.nais.io"